[package]
name = "ar_pe_ce_macro"
version = "0.0.1"
authors = [ "Wojciech Polak <frondeus@gmail.com>" ]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
itertools = "0.10.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "1.0", features = ["extra-traits"] }
